### ISSUE TITLE
Default Media Query Breakpoints

### ISSUE THREAD

**Issue by oleersoy** [suitcss/utils-size#24] opened 2015-09-10 15:55 UTC
Right now if we run the build, the media query breakpoint classes are not generated, because the index.css file is missing defaults for these parameters.  It would be great if SUIT provided default best practice parameters...probably in a separate file `suit-media-query-breakpoint-defaults` that is imported in index.css.  If this is done the parameters can be removed from `test/test.css`.

**Comment by oleersoy** [comment] 2015-09-16 22:55
Another related question is what the simplest workflow for using default parameters or changing them?  It would be nice if the documentation said something like...if you want to customize these parameters then...

Looking at the test there's an obvious answer and that is to include the parameter customizations in `index.css`.  But what if `index.css` contains 10 different modules?  One idea would be something like:

Source directory containing source css:
`src/main/css/suitcss-utils-size.css`

And inside `suitcss-utils-size.css`:
```css
import  suitcss-utils-size-defaults
import suitcss-utils-size
```
or
```css
@custom-media --sm-viewport (min-width:0px) and (max-width:40px);
@custom-media --md-viewport (min-width:40px) and (max-width:60px);
@custom-media --lg-viewport (min-width:60px);

import suitcss-utils-size
```

Hopefully the above customizations would rarely be necessary to hand code, because SUIT could provide or reference default packages containing parameters covering 99% of all use cases.  For example SUIT uses px breakpoints in the test, but @philipwalton uses em units in his flexbox article:
[Flexbox Article](http://philipwalton.github.io/solved-by-flexbox/demos/grids/).

Moving along compile `src/main/css/suitcss-utils-size.css`to:
`target/css/suitcss-utils-size.css`

The css resource `target/css/suitcss-utils-size.css` would now contain either the customizations or the defaults.

In case the directory structure looks strange it comes from [Maven Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html).  The general idea is to have a standard set of directories for source and a corresponding set for compiled individual sources, and then another for minified sources, etc.  This way resources can be inspected at each stage of the build.

Javascript would therefore go in:
`src/main/javascript/`
Coffeescript:
`src/main/coffeescript`
Html
`src/main/html`

And so on...

**Comment by simonsmith** [comment] 2015-10-01 22:41
The idea is that these utils are used as part of your application that already defines these values. If you have a look at the SUIT theme you'll see those values (and any other custom property overrides) being declared - https://github.com/suitcss/theme/blob/master/lib/theme.css#L12-L14

Another example - https://github.com/simonsmith/simonsmith.io/blob/master/source/stylesheets/src/theme.css

**Comment by oleersoy** [comment] 2015-10-01 23:49
It feels a little bit like "Media Query Breakpoint utilities, no batteries included".  I'm assuming that there there has to be a set of breakpoints that are used 99.99% of the time and that we can save users from having to manually specify the breakpoints in these instances?

**Comment by oleersoy** [comment] 2015-10-02 02:12
Also suppose that these breakpoints are considered the defaults:

```css
@custom-media --sm-viewport (min-width:320px) and (max-width:640px);
@custom-media --md-viewport (min-width:640px) and (max-width:960px);
@custom-media --lg-viewport (min-width:960px);
```
And therefore included as such in tests that perform testing of the utilities that are responsive.  If the breakpoint defaults are changed, then we should probably change them across the tests in order to stay consistent, but in order to do this each test / package has to be updated individually.

**Comment by timkelty** [comment] 2015-10-02 02:51
> I'm assuming that there has to be a set of breakpoints that are used 99.99% of the time

Do you mean like device specific breakpoints? That seems like way too much of a moving target to me to include here.

**Comment by timkelty** [comment] 2015-10-02 02:59
Perhaps for the tests we could just include the stuff from https://github.com/suitcss/theme instead of sticking in the breakpoints. Easier to do across different repos that way too.

**Comment by simonsmith** [comment] 2015-10-02 08:50
> I'm assuming that there has to be a set of breakpoints that are used 99.99% of the time and that we can save users from having to manually specify the breakpoints in these instances

I use a different set in nearly every project, but if users need a set of defaults then installing SUIT via the `theme` is a viable route, as @timkelty says

**Comment by oleersoy** [comment] 2015-10-02 15:36
@simonsmith can we keep these open until I have had a chance to respond?  I find organizations that encourage the person who originated the ticket to close it much more welcoming.

**Comment by simonsmith** [comment] 2015-10-02 15:39
Fair enough yeah, I've jut been trying to sweep up the dozens of issues that are dotted around.

**Comment by oleersoy** [comment] 2015-10-02 16:01
Cool - thanks for keeping it open.  What I like about SUIT is that each package is much smaller and more modular than other projects built with say LESS or SASS.  Usually the imports make sense and are easy to reason about.  So having a default set of breakpoints that all packages can rely still seems like it makes sense to me.

Also there may be one set of breakpoints that are used 90% of the time, and 4 others that covers the remaining 10%.  There has to be a limit to the sets that make sense, because of the nature of what breakpoints are for, or am I missing something?

Having a process that allows for simple a simple way to plug in packaged breakpoints that work well in described scenarios seems like it should make SUIT more attractive.

**Comment by timkelty** [comment] 2015-10-02 16:09
> Also there may be one set of breakpoints that are used 90% of the time, and 4 others that covers the remaining 10%. There has to be a limit to the sets that make sense, because of the nature of what breakpoints are for, or am I missing something?

I'm not totally sure what you're looking for — Seems like we have the sensible defaults you're looking for already, here: https://github.com/suitcss/theme/blob/master/lib/theme.css#L12-L14

They roughly cover:
- phones (sm)
- tablets (portrait) (md)
- desktop/tablets (landscape) and up

I do think it's a good idea to include the theme in all the tests, rather than duplicating those breakpoints in the test.

As for actual usage in a project, the idea (as I understand it) is you make your own theme (perhaps starting with and editing suitcss-theme). That way you have your breakpoints defined just as they would be in the tests, and you can customize from there.

**Comment by simonsmith** [comment] 2015-10-02 16:17
The size utilities tend to work best with global structure like the grid. Then components are free to use their own break points for tweaking descendant layout. 

The danger here is trying to make SUIT some super complicated and configurable framework when I don't think such a use case exists. 

Be good to keep it simple.

**Comment by oleersoy** [comment] 2015-10-02 16:30
I love simple!  Reading from the I probably over complicated this with the initial description.  I think we agree that the current set of defaults are sensible across most devices.

I think it should work like this:

Inside `theme.css`
```css
@import suit-css-breakpoint-defaults
...
```

Inside `utils-size.css`:
```css
@import suit-css-breakpoint-defaults
...

This seems like it makes more more sense, because a theme is orthagonal to the sizing utilities?

**Comment by simonsmith** [comment] 2015-10-02 16:34
I'm not sure how this different from the current defaults in theme, you're just giving it a different name? 

One thing is you don't need to use the suit theme, just define the break points wherever makes sense. 

In my blog I do it like so https://github.com/simonsmith/simonsmith.io/blob/master/source/stylesheets/src/theme.css but this file could be called anything. 

As long as the build tools can see it then it'll work.

**Comment by oleersoy** [comment] 2015-10-02 17:16
> I'm not sure how this different from the current defaults in theme, you're just giving it a different name? 

I think we are very close on this.  I'm separating the defaults from the theme and naming them `defaults`.  In terms of a dependency structure though, it makes sense for the theme to depend on the defaults, because the theme uses them.  It also makes sense for `utils-size` to depend on the defaults.  Both packages use the defaults.  If the defaults change, then both packages, and any other packages that use the defaults, get the changes.  The `utils-size` package does not depend on the remaining content of the `theme.css` module, so that's the reason that separating the two makes sense.

> One thing is you don't need to use the suit theme, just define the break points wherever makes sense. 

True, but it's easier and DRYer to do:
``` css
@import suit-breakpoint-defaults
```
Than redefining the contents of `suit-breakpoint-defaults` everywhere, and having to update the contents of `suit-breakpoint-defaults` everywhere during refactoring.

> In my blog I do it like so https://github.com/simonsmith/simonsmith.io/blob/master/source/stylesheets/src/theme.css but this file could be called anything. 

BTW - I like your blog.  Need to read up on it some more.  Good stuff!

Back to the conversation.  So I think we are basically saying the same thing then.  We agree that the defaults should be in a a file and that that file should be used by targets where it makes sense.

**Comment by simonsmith** [comment] 2015-10-02 17:22
> We agree that the defaults should be in a a file and that that file should be used by targets where it makes sense.

Yep, but I think my point is that `theme.css` is already doing this right now. However, I realise that not everyone uses theme when they use SUIT, so where do they define their breakpoints?

It's likely that everyone will have some form of manifest to bring their app together, so that is where the defaults can live.

Example:

**index.css**
``` css
/**
 * SUIT
 */
@import "suitcss-components-grid";
@import "suitcss-utils-layout";
@import "suitcss-utils-size/lib/size-sm";
@import "suitcss-utils-size/lib/size-md";

/**
 * Components
 */
@import "./components/highlight";
@import "./components/icon";
@import "./components/container";
@import "./components/entry";
@import "./components/entry-list";
@import "./components/header";

/** Defaults **/
@custom-media --sm-viewport (min-width: 36.25em);
@custom-media --md-viewport (min-width: 49.375em);
@custom-media --lg-viewport (min-width: 72.1875em);
```

My point is, nothing in SUIT needs to change to accommodate this flexibility. I'm not sure how using a `suit-breakpoints-defaults.css` gives you any more help, it just means another layer of abstraction.

**Comment by oleersoy** [comment] 2015-10-02 18:02
Suppose the designer has 15 index.css files that all have this snippet in them:

```css
@custom-media --sm-viewport (min-width: 36.25em);
@custom-media --md-viewport (min-width: 49.375em);
@custom-media --lg-viewport (min-width: 72.1875em);
```
And suppose that the designer realizes that it should have been:
```css
@custom-media --sm-viewport (min-width: 50em);
@custom-media --md-viewport (min-width: 70em);
@custom-media --lg-viewport (min-width: 100em);
```
If the breakpoints are defined in their own file, then the designer can just redefine them in one place and be done, instead of doing 15 updates.

As far as SUIT goes I think it's a pretty trivial change.  Any package that uses the defaults would just declare them as a dependency and `@import` them.

**Comment by timkelty** [comment] 2015-10-02 19:06
@oleersoy I don't see how separating to `suit-breakpoints-defaults.css` would solve your example's problem.

In that case you could create your _own_ `breakpoints.css` with that in it, and `@import breakpoints.css` in each of your 15 index.css files.

...which is how `suitcss-theme` works.

Consider the previously mentioned file: https://github.com/simonsmith/simonsmith.io/blob/master/source/stylesheets/src/theme.css

Just include that at the top of each of your css files and you're good.

**Comment by oleersoy** [comment] 2015-10-02 19:10
Creating my own each time is more work than simply declaring it as a dependency.  Also having other SUIT packages depend on a theme package creation ambiguity / indirection.

**Comment by oleersoy** [comment] 2015-10-02 19:12
How does creating my own each time solve the problem?

**Comment by timkelty** [comment] 2015-10-02 19:52
@oleersoy Your example referred to someone changing the values, in which case you'd have to have them declared your self anyway.

Part of what I like about how it is structured now, is it encourages users to use the theme concept with every build. If your project css starts with "grab a copy of suitcss-theme, edit values as needed, continue on to project-specific css".

You could also achieve exactly what you're describing by doing:
```
@import suitcss-theme/lib/theme.css
```

Then you can either redefine any custom-media/props after the import, or scrap the import for your own version.

**Comment by simonsmith** [comment] 2015-10-02 20:05
Yeah, the point of the `theme.css` is to be bespoke to your project, so the second you need to change it then the included `breakpoint-defaults` (if it existed) becomes pointless.

> Lets assume there are 15 different index.css files in 15 different project repositories.

I feel like that's an extreme case that would never happen, but if it did you just create one global theme file at a top level and import it.

**Comment by timkelty** [comment] 2015-10-02 21:04
I feel like a guide on "how to use SUITCSS in a project" could mitigate a lot of this.

For example:
- *Step 1.* create a theme for your project. Start with `suitcss-theme` and customize as needed.
- *Step 2.* `@import suit-base`, your new theme, any utilities or components you want.
- *Step 3.* profit?

And then of course this process could be built into a Yeoman generator for a quick start.

**Comment by oleersoy** [comment] 2015-10-02 22:19
I like the profit part :+1: .  There's an easy way for us all to win here that does not preclude from any path of development.

1) Create a separate repository for media query breakpoint defaults / settings
2) Put the defaults in there

And we are all good.  Sound OK?

**Comment by simonsmith** [comment] 2015-10-02 22:22
> 1) Create a separate repository for media query breakpoint defaults / settings

Yeah, I think you can store your project specific settings however you wish, import them and you're done.

**Comment by oleersoy** [comment] 2015-10-03 04:15
Yes but I really would like it to be part of SUIT CSS such that it looks like a set of defaults that are "Best practice defaults".  If we do this and no one ever logs issues against the defaults, then this will have zero impact on your workflow in terms of additional effort or anything else.  The total cost will be a 5 minute setup of the repo.

**Comment by oleersoy** [comment] 2015-10-03 04:32
A theme and breakpoints are two orthagonal concepts.  We do not need to have a theme to create responsive utilities for example.  So if we keep these separate we both get what we are asking for.  We can import the breakpoints into the theme, and we can import the breakpoints into the responsive utilities.

**Comment by simonsmith** [comment] 2015-10-03 06:09
Let's just keep the theme file with the break points. It's doing exactly the same thing and this proposal is just to create another file for the sake of it.

**Comment by oleersoy** [comment] 2015-10-03 12:56
@simonsmith do media query defaults evolve over time?

**Comment by simonsmith** [comment] 2015-10-04 09:54
I think we've discussed this issue past being useful now. I think the general consensus here is that in every project the media query breakpoints used by the `utils-size` will differ from project to project and therefore adding a `default-breakpoints.css` would be redundant as the developer would need to change them straight away.

For the cases where people _are_ happy to accept the defaults, well they can just `@import "theme.css"`

SUIT is designed to accompany your own components and theme files, rather than being the only thing you use. Therefore it is encouraged (and necessary) that users create their own and this makes it simple to setup any custom media defaults and any other overrides that need to be reused across the project.

Any other thoughts @timkelty @giuseppeg @necolas? Otherwise I think we can consider this closed.

**Comment by oleersoy** [comment] 2015-10-04 15:35
So @simonsmith what you are saying is that all projects use different media query breakpoints for medium devices?  Could you please share some of the criteria that you use to select a breakpoint for a medium device?  What are the values you usually go with?

**Comment by simonsmith** [comment] 2015-10-04 16:25
> all projects use different media query breakpoints for medium devices?

Impossible to say all, but from experience none that I've worked on have got away with just using what Bootstrap or SUIT provides and just getting on with it. One of the complications of using the default SUIT media queries in `theme.css` is that they cover a range i.e:

``` css
@custom-media --md-viewport (min-width:640px) and (max-width:960px);
```

Whilst this can be a good starting point I've found sometimes I need to access the min and max separately, requiring me to write something like:

``` css
/**
 * Breakpoints
 */
@custom-media --xs-min-viewport (min-width: 400px);
@custom-media --xs-max-viewport (max-width: 599px);

@custom-media --sm-min-viewport (min-width: 600px);
@custom-media --sm-max-viewport (max-width: 769px);

@custom-media --md-min-viewport (min-width: 770px);
@custom-media --md-max-viewport (max-width: 1007px);

@custom-media --lg-min-viewport (min-width: 1008px);
```

The above sizes are from working on a BBC product where they have already determined the best breakpoints for their expected audience.

When picking sizes yourself I think it's best to stick to what suits the widths of your expected content, rather than picking a phone media query, a tablet media query etc. For example the widths used on my blog were determined by letting the content get as wide as possible before it started to look odd on that device size, then a media query is needed to step in and improve the layout. This divorces the choice from device size (which changes constantly) to content size (which tends to be more predictable).

> Design the content to fit on a small screen size first, then expand the screen until a breakpoint becomes necessary. This allows you to optimize breakpoints based on content and maintain the fewest number of breakpoints possible.

https://developers.google.com/web/fundamentals/layouts/rwd-fundamentals/how-to-choose-breakpoints?hl=en

Perhaps the focus of this issue could be, are the SUIT default media queries (in theme.css) ideal, or could they be updated? Do we need more sizes (an `xs` for example)?

**Comment by oleersoy** [comment] 2015-10-05 04:14
> Perhaps the focus of this issue could be, are the SUIT default media queries (in theme.css) ideal, or could they be updated? Do we need more sizes (an xs for example)?

Yes!  Much better :+1: .  I think we're starting to get on the same page here :).  BTW - I'm assuming that they could be updated and that this is a continuous process.

I'm just going to reboot my the terminology.  When I'm referring to a 'default media query breakpoint', what I actually mean is [Media Queries for Common Device Breakpoints](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints), which is what @timkelty noted originally.  

When looking for recommendations on how to set specify CSS based on device size, or [Media Queries for Common Device Breakpoints](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints), there's a lot of variation.  For example SUIT CSS testing and theme defaults look like this:

```css
@custom-media --sm-viewport (min-width:320px) and (max-width:640px);
@custom-media --md-viewport (min-width:640px) and (max-width:960px);
@custom-media --lg-viewport (min-width:960px);
```
And there are more recommendations here:
[media-queries-for-standard-devices](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/) and here [Media Queries for Common Device Breakpoints](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints).  Which is probably the tip of the mountain.  I've seen other variations with `rem` units, etc.

So suppose that all I'm interested in is a really simple design scenarios using `utils-size` responsive utilities to for example resize a grid, like the one in [Html5Boilerplate](https://html5boilerplate.com/), such that for small devices there's a single column, for medium devices there's 2 columns, and for large devices there's 3 columns in the first row, and one grid cell centered below them in the second row.

Which breakpoint values should I use to generate the utils-size responsive utilities?  So at this stage I might not need the rest of the content in theme.css.  When I think of creating a theme I think of jqueryui themes, and dojo themes, etc.  Things that are really heavy, and are utilized across the entire application / site.  In this case I just want to generate the `utils-size` responsive utilities using the most lighweight approach possible, while having confidence [Media Queries for Common Device Breakpoints](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints) I have selected are going to do a good job.  Having:

```css
/* Main colors */
:root {
  --color-blue:       #0071ac;
  --color-light-blue: #0d85c1;
  --color-pink:       #ac6cae;
}

/**
 * Fonts
 */
:root {
  --font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
}
```
Also included, when all I need are a well tested set of device specific breakpoints, could introduce problems.  Again I understand that this could be a great starting point 80% of the time, but I think it would be nice if the 20% that we need something more lightweight SUIT provides the isolated set of breakpoints and minimizes the effort involved in the corresponding workflow for their utilization over the life cycle of the product.

Having a repository that contains peer / community [Media Queries for Common Device Breakpoints](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints) would be a valuable resource when performing simple responsive designs.  If it adds other breakpoints that are commonly utilized in specific well defined scenarios that are a good fit for SUIT CSS components and utilities, even better.

WDYT?

**Comment by giuseppeg** [comment] 2015-10-05 05:39
<blockquote>I think the general consensus here is that in every project the media query breakpoints used by the utils-size will differ from project to project and therefore adding a default-breakpoints.css would be redundant as the developer would need to change them straight away.</blockquote>
I agree.

In general SUIT CSS is a methodology rather than a framework ala Bootstrap so in my opinion providing ready to use CSS packages is outside of the scope of this org.

Anybody is free to create and publish to npm a *suitcss-"Media Queries for Common Device Breakpoints"* package and we can mention it in the docs.

By the way [suitcss/theme](https://github.com/suitcss/theme) is just an example theme.

**Comment by simonsmith** [comment] 2015-10-05 06:26
> Which breakpoint values should I use to generate the utils-size responsive utilities?

I think this a good question but not for SUIT to answer. As @giuseppeg says, SUIT is more a methodology than framework. I think selecting the breakpoints should remain a decision of the developer, not SUIT.

**Comment by timkelty** [comment] 2015-10-05 13:03
Not to confuse the issue more, but — if we decide to use some sort of dynamic generation of classes (https://github.com/suitcss/utils-size/issues/28), the question of classes and breakpoints are included could be moot. Then you could add xs, xxs, xl, etc...at whatever breakpoints you wanted.

Furthermore, targeting specific devices with media queries is [probably the wrong approach](https://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints), and shouldn't be SUIT's job. Your breakpoints ideally are determined by where you content shifts naturally, as @simonsmith mentioned.

@oleersoy if you really did want to target a device, I'd simply suggest doing this, and importing this at the top of all your project's files:

```
@import 'suitcss-utils-size`;

// Galaxy S5
@custom-media --sm-viewport (only screen and (min-device-width: 360px) and (max-device-height: 640px) and (orientation : landscape) and (-webkit-device-pixel-ratio: 3));
```

**Comment by timkelty** [comment] 2015-10-05 13:06
Perhaps what is confusing is that utils/components have their `custom-properties` pre-defined in the project, but not their `custom-media`.

Presumably this is because if you don't have a particular `custom-media` defined, the whole block will get removed when processing.

**Comment by simonsmith** [comment] 2015-10-05 13:08
I think just adding a note to the README about needing to define `@custom-media` somewhere is all that is required to close this issue.

**Comment by oleersoy** [comment] 2015-10-05 13:57
@simonsmith issues usually close themselves naturally  once all the parties draw conclusions that's in the best interest of the project.  Allowing it to work itself out is what is going to achieve the best result.

>In general SUIT CSS is a methodology rather than a framework ala Bootstrap so in my opinion providing ready to use CSS packages is outside of the scope of this org.

>Anybody is free to create and publish to npm a suitcss-"Media Queries for Common Device Breakpoints" package and we can mention it in the docs.

That's basically all I'm asking for.  For the "Media Queries for Common Device Breakpoints" to be used as the test defaults and recommended defaults for common devices.  Also as I have noted this is different from [Possibly the Wrong Approach](https://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints).

> Perhaps what is confusing is that utils/components have their custom-properties pre-defined in the project, but not their custom-media.

SUIT seems to be following a pattern of providing custom defaults when it makes sense.  I think developers like this.  If the project can make it simpler for them, we will get more love back.

There are scenarios where the developer knows that they do need device specific breakpoints, and this accommodates that scenario.  All this would do is allow the capture of instances where the breakpoints are not doing a good job of detecting the a device.

Since SUIT has already gone down the road of providing responsive utilities, it does not hurt to provide a solid standard starting point for those utilities.

> Presumably this is because if you don't have a particular custom-media defined, the whole block will get removed when processing.

That's another thing that can be better explained.  If not breakpoints are provided, then a generic set of non responsive utilities are built.  Like @simonsmith says, we can add a note in the README explaining this better.

I think that if the README says something like:

==========================================

To generate a set of utilities targeting specific device sizes, do the following:
```css
@import suit-device-specifc-media-query-breakpoints
@import utils-size
```
Note that rather than targeting devices specifically, it may be better to follow the approach advocated by [Possibly the Wrong Approach](https://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints).

===========================================

At least now both options are covered cleanly.  

> Not to confuse the issue more, but — if we decide to use some sort of dynamic generation of classes (#28), the question of classes and breakpoints are included could be moot. Then you could add xs, xxs, xl, etc...at whatever breakpoints you wanted.

I think this would be a really good thing.  We basically need it in order to generate the `source-order` flex box utilities anyways.  It would also provide a much more powerful device detection capabilities for those that need it.  

@timkelty since SUIT enables the generation of responsive utilities, it would be great if it had a good set of defaults, and showed how to build using those defaults, in order to minimize the workflow for developers that do need to target specific devices.

At a minimum this makes SUIT more consistent across packages and allows it to provide a more comprehensive solution.  It would also hopefully encourage feedback in the event that some of the device specific breakpoints are off.

**Comment by simonsmith** [comment] 2015-10-05 14:06
> issues usually close themselves naturally once all the parties draw conclusions that's in the best interest of the project. Allowing it to work itself out is what is going to achieve the best result.

From what I can tell from reading this issue all the parties except yourself disagree with the idea of providing media query defaults in here, that feels like the issue is resolving itself. We can't just add every feature that one single person requires. 

I'm still not convinced there is a use case for these additions beyond a note in the README. Having worked with SUIT amongst several developers not one has raised any issue with needing default breakpoints. It's trivial and encouraged to handle this yourself.

Why can't the README just say this?

``` css
@custom-media --sm-viewport (min-width:320px) and (max-width:640px);
@custom-media --md-viewport (min-width:640px) and (max-width:960px);
@custom-media --lg-viewport (min-width:960px);
@import utils-size
```

Identical outcome for no extra complexity. 

I think we're all opposed to the idea of SUIT trying to be Bootstrap, and this feels like a feature that I don't see any need for other for your use @oleersoy. 

Maybe if you're using it in a project where this is needed you could fork it, add it and see what the feedback is amongst the other developers you work with. Otherwise I think we can all agree this issue has been discussed beyond usefulness and is best closed as a `wontfix`

**Comment by timkelty** [comment] 2015-10-05 14:24
Certainly not trying to shut your issue down, @oleersoy but I'm on the same page as @simonsmith.

It sounds like you're asking the SUIT repo(s) to maintain a list of `custom-media` definitions for devices, along [these lines](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints).

> It would also hopefully encourage feedback in the event that some of the device specific breakpoints are off.

I think that's precisely what we don't want to deal with; a canonical list of ever-changing device breakpoints.

While there are certainly some use-cases for targeting devices in such a way, it seems to be the consensus of others in this thread that SUIT isn't the right place to manage this.

That said, if it is something you're really looking for, why not just publish yourself a repo with those queries defined as `custom-media` definitions and import it into your files?

I think you're definitely right about README and startup examples needing to be better. I think as we migrate to a monorepo this will become easier.

**Comment by oleersoy** [comment] 2015-10-05 15:23
OK Fair enough.  You are right that it could easily be managed outside of SUIT.  I do think that that SUITs unwillingness to provide end to end examples and content is one of the reasons it does not have much of a pulse ATM even though the underlying concepts are brilliant.  Anyways it sounds like we are ready to wrap this up, so I'll close the issue.  Thank you all for participating.

**Closed** 2015-10-05 15:23 UTC

**Comment by timkelty** [comment] 2015-10-05 15:25
Yep - more examples and startup docs for sure.

**Comment by oleersoy** [comment] 2015-10-05 23:03
BTW - @simonsmith  - thanks for mentioning Bootstrap.  I think this is precisely what I'm looking for:
[Bootstrap Responsive Utilities](http://v4-alpha.getbootstrap.com/layout/responsive-utilities/)
